plugins {
    id 'com.gtnewhorizons.retrofuturagradle' version '1.3.27'
}

version = '1.0.0'
group = 'com.weaponpersonalities'
archivesBaseName = 'WeaponPersonalities'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
        vendor = JvmVendorSpec.AZUL
    }
    withSourcesJar()
}

minecraft {
    mcVersion = '1.12.2'
    username = 'Developer'
    useDependencyAccessTransformers = true
}

repositories {
    maven {
        name = 'forge'
        url = 'https://maven.minecraftforge.net'
    }
    maven {
        name = 'SpongePowered'
        url = 'https://repo.spongepowered.org/maven'
    }
}

dependencies {
    implementation('net.minecraftforge:forge:1.12.2-14.23.5.2855:universal')
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', project.minecraft.mcVersion

    filesMatching('mcmod.info') {
        expand 'version': project.version, 'mcversion': project.minecraft.mcVersion
    }
}

jar {
    manifest {
        attributes([
            'Specification-Title'     : 'Weapon Personalities',
            'Specification-Vendor'    : 'WeaponPersonalities',
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.version,
            'Implementation-Vendor'   : 'WeaponPersonalities',
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}
