buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '2.3-SNAPSHOT', changing: true
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

version = '1.0.0'
group = 'com.weaponpersonalities'
archivesBaseName = 'weaponpersonalities'

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

minecraft {
    version = '1.12.2-14.23.5.2855'
    runDir = 'run'
    mappings = 'stable_39'
    useDepAts = true
}

dependencies {
    // Forge is included via the minecraft block above
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': project.minecraft.version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

jar {
    manifest {
        attributes([
            'Specification-Title'     : 'Weapon Personalities',
            'Specification-Vendor'    : 'WeaponPersonalities',
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.version,
            'Implementation-Vendor'   : 'WeaponPersonalities',
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}
