plugins {
    id 'com.gtnewhorizons.retrofuturagradle' version '1.3.32'
}

version = '1.0.0'
group = 'com.weaponpersonalities'
archivesBaseName = 'WeaponPersonalities'

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
    maven { url = 'https://libraries.minecraft.net/' }
    mavenCentral()
}

minecraft {
    mcVersion = '1.12.2'
    username = 'Developer'
    mcpMappingChannel = 'stable'
    mcpMappingVersion = '39'
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', minecraft.mcVersion

    filesMatching('mcmod.info') {
        expand 'version': project.version, 'mcversion': minecraft.mcVersion
    }
}

jar {
    manifest {
        attributes([
            'Specification-Title'     : 'Weapon Personalities',
            'Specification-Vendor'    : 'WeaponPersonalities',
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.version,
            'Implementation-Vendor'   : 'WeaponPersonalities',
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}
